package gui2;

import ca.CA5;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.image.BufferedImage;
import java.awt.geom.Rectangle2D;
import java.io.File;
import java.io.IOException;

/**
 *
 * @author tadaki
 */
public class DrawPanel extends javax.swing.JPanel implements Runnable {

    private volatile boolean running = false;
    private CA5 ca;
    private final int sleep = 20;
    private double f;
    private int tmax;
    private int t = 0;
    private BufferedImage image;

    /**
     * Creates new form DrawPanel
     */
    public DrawPanel() {
        initComponents();
    }

    @Override
    public void run() {
        while (running) {
            int cells[] = ca.getCells();
            Graphics2D g = (Graphics2D) image.getGraphics();
            g.setColor(Color.red);
            for (int i = 0; i < cells.length; i++) {
                if (cells[i] == 1) {
                    Rectangle2D.Double r = new Rectangle2D.Double(i * f, t * f, f, f);
                    g.fill(r);
                }
            }
            repaint();
            ca.update();
            t++;
            if (t == tmax) {
                stop();
                try {
                    String filename = "CA5-" + ca.getRule() + ".png";
                    File file = new File(filename);
                    javax.imageio.ImageIO.write(image, "png", file);
                    System.out.println(filename);
                    
                } catch (IOException ex) {
                    System.err.println(ex);
                }
            }
            try {
                Thread.sleep(sleep);
            } catch (InterruptedException ex) {
            }

        }
    }

    @Override
    public void paintComponent(Graphics g) {
        g.drawImage(image, 0, 0, this);
    }

    public void start() {
        running = true;
        image = new BufferedImage(getWidth(), getHeight(), BufferedImage.TYPE_INT_RGB);
        clear();
    }

    public void clear() {
        if (image == null) {
            image = new BufferedImage(getWidth(), getHeight(), BufferedImage.TYPE_INT_RGB);
        }
        Graphics2D g = (Graphics2D) image.getGraphics();
        g.setColor(getBackground());
        g.fillRect(0, 0, getWidth(), getHeight());

    }

    public void stop() {
        running = false;
    }

    public void setCA(CA5 ca) {
        this.ca = ca;
        f = this.getWidth() / ca.getN();
        tmax = (int) (this.getHeight() / f);
        System.out.println(ca.getN());
        t = 0;
    }

    public void setT(int t) {
        t = 0;
        clear();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
